axf/app/urls.py
from django.conf.urls import url, include
from app import views

urlpatterns = [
    url(r'^home/$',views.home,name='home'),
    url(r'^market/$',views.market,name='market'),
    url(r'^queryfood/(\d+)/(\d+)/(\d+)/$',views.queryfood,name='queryfood'),
    url(r'^cart/$',views.cart,name='cart'),
    url(r'^mine/$',views.mine,name='mine'),

    # 登录
    url(r'^login/$',views.login,name='login'),
    url(r'^logout/$',views.logout,name='logout'),

    # 购物车
    url(r'^addcart/$',views.addCart,name='addcart'),
    url(r'^subcart/$',views.subCart,name='subcart'),
    url(r'^changestate/$',views.changestate,name='changestate'),
    url(r'^allselect/$',views.allselect,name='allselect'),
]

axf/axf1805/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/',include("app.urls",namespace='app')),
]

axf/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/swiper.css' %}">
    {% block extCSS %}

    {% endblock %}
    <title>{{ title }}</title>
</head>
<body>

{% block header %}

{% endblock %}

{% block content %}

{% endblock %}

{% block footer %}

{% endblock %}

<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
<script type="text/javascript" src="{% static 'js/swiper.jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/base.js' %}"></script>
{% block EXTJS %}

{% endblock %}
</body>
</html>

axf/templates/base_main.html
{% extends 'base.html' %}
{% load static %}
{% block extCSS %}

    <link rel="stylesheet" href="{% static 'css/base.css' %}">

{% endblock %}


{% block header %}

    <header></header>

{% endblock %}

{% block footer %}

    <footer>

        <a href="{% url 'app:home' %}" class="home">

            <dl>

                <dt>
                    <span></span>
                </dt>
                <dd>首页</dd>

            </dl>

        </a>
        <a href="{% url 'app:market' %}" class="market">

            <dl>

                <dt>
                    <span></span>
                </dt>
                <dd>闪购</dd>

            </dl>

        </a>
        <a href="{% url 'app:cart' %}" class="cart">

            <dl>

                <dt>
                    <span></span>
                </dt>
                <dd>购物车</dd>

            </dl>

        </a>
        <a href="{% url 'app:mine' %}" class="mine">

            <dl>

                <dt>
                    <span></span>
                </dt>
                <dd>我的</dd>

            </dl>

        </a>

    </footer>

{% endblock %}

axf/templates/cart.html
{% extends 'base_main.html' %}
{% load static %}
{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'app/cart/cart.css' %}">
{% endblock %}
{% block EXTJS %}
    <script type="text/javascript" src="{% static 'app/cart/js/cart.js' %}"></script>
{% endblock %}

{% block content %}

    <div id="cart">

        <h3>购物车</h3>

        <div class="full">

            <section class="clear">

                <ul>
                    <li>收货人:宝宝
                        <div><p><span><a href="#">修改&gt;</a></span></p></div>
                    </li>
                    <li>电话:120</li>
                    <li>收货地址:宝胜北里西区28号天丰利商城</li>

                </ul>


                <div class="bill">

                    <p>闪送超市</p>

                    <a href="#">凑单专区</a>

                    <p>满100减99</p>

                </div>

                <p class="delivery">

                    <span>收货时间:</span>
                    <span>一小时送达</span>
                    <a href="#">可送达&gt;</a>
                </p>

                <p class="delivery">
                    <span>留言:</span>
                    <input type="text" placeholder="有什么特殊需求">
                </p>


                <menu>

                    <ul>
                        {% for cart in carts %}
                            <li class="menuList">
                                <div class="confirm">
                                    <span class="selector1" is_select="{{ cart.is_selected }}" gid="{{ cart.goods_id }}">
                                        {% if cart.is_selected %}
                                            <span>√</span>
                                        {% else %}
                                            <span></span>
                                        {% endif %}

                                    </span>
                                </div>
                                <a href="">
                                    <img src="{{ cart.goods.productimg }}" alt="">
                                    <p>{{ cart.goods.productlongname }}</p>
                                </a>
                             <section>
                                <button   class="subShopping">-</button>
                                <span>0</span>
                                <button class="addShopping">+</button>
                            </section>
                            </li>
                        {% endfor %}
                        <li class="payTheBill">

                            <div class="confirm" id="all_select">
                                <span id="allselected">
                                    {% ifequal allselect '1' %}
                                         <span>√</span>
                                    {% else %}
                                        <span></span>
                                    {% endifequal %}


                                </span>
                            </div>

                            <p>
                                <span >全选</span>
                                <span>总价:</span>
                            </p>

                            <a href="#">下单</a>

                        </li>

                    </ul>

                </menu>


            </section>


        </div>


    </div>


{% endblock %}

axf/templates/home.html
{% extends 'base_main.html' %}
{% load static %}
{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'app/home/home.css' %}">
{% endblock %}

{% block EXTJS %}
    <script type="text/javascript" src="{% static 'app/home/js/home.js' %}"></script>
{% endblock %}
{% block content %}

    <div id="home">
        {# 轮播 #}
        <div id="topSwiper" class="swiper-container">
            <div class="swiper-wrapper">
                {% for wheel in wheels %}
                     <div class="swiper-slide">
                        <a href="#"><img src="{{ wheel.img }}"></a>
                    </div>
                {% endfor %}
            </div>

        </div>
        {# 导航 #}
        <div class="topMenu">
            <nav>
                <ul>
                    {% for nav in navs %}
                        <li>
                            <a href="#">
                                <img src="{{ nav.img }}" alt="">
                                <span>{{ nav.name }}</span>
                            </a>
                        </li>
                    {% endfor %}

                </ul>
            </nav>
        </div>

        {# 每日必抢 #}
        <div class="swiper-container"  id="swiperMenu">
            <ul class="swiper-wrapper">
                {% for mustbuy in mustbuys %}
                    <li class="swiper-slide">
                        <a href="#">
                            <img src="{{ mustbuy.img }}" alt="">
                        </a>
                    </li>
                {% endfor %}
                
            </ul>
        </div>
        {# 商店 #}
        <div class="CVS">
            <h2>
                <img src="{{ shop1.img }}" alt="{{ shop1.name }}">
            </h2>
            <fieldset>
                {% for shop in shop2_3 %}
                     <a href="">
                        <img src="{{ shop.img }}" alt="{{ shop.name }}">
                    </a>
                {% endfor %}



            </fieldset>
            <ul>
                {% for shop in shop7_11 %}
                    <li>
                        <a href="">
                            <img src="{{ shop.img }}" alt="">
                            <span>{{ shop.name }}</span>
                        </a>

                    </li>
                {% endfor %}

            </ul>
            <ol>
                {% for shop in shop7_11 %}
                    <li>
                        <a href=""><img src="{{ shop.img }}" alt="{{ shop.name }}"></a>
                    </li>
                {% endfor %}

            </ol>
        </div>
        {# 主要信息展示 #}
        <div class="mainInfo">
            {% for mainshow in mainshows %}
                <section>
                    <h3>
                        {{ mainshow.name }}
                        <a href="">更多</a>
                        <span></span>
                    </h3>
                    <div>
                        <a href="#"><img src="{{ mainshow.img }}" alt=""> </a>
                    </div>
                    <ul>
                        <li>
                            <a href="#">
                                <img src="{{ mainshow.img1 }}" alt="">
                                <span>{{ mainshow.longname1 }}</span>
                                <span>{{ mainshow.price1 }}</span>
                                <s>{{ mainshow.marketprice1 }}</s>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="{{ mainshow.img2 }}" alt="">
                                <span>{{ mainshow.longname2 }}</span>
                                <span>{{ mainshow.price2 }}</span>
                                <s>{{ mainshow.marketprice2 }}</s>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="{{ mainshow.img3 }}" alt="">
                                <span>{{ mainshow.longname3 }}</span>
                                <span>{{ mainshow.price3 }}</span>
                                <s>{{ mainshow.marketprice3 }}</s>
                            </a>
                        </li>
                    </ul>
                </section>
            {% endfor %}

        </div>
    </div>

{% endblock %}

axf/templates/login.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <div class="container">
        <form class="form-horizontal" action="{% url 'app:login' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username" class="col-sm-2 control-label">用户名</label>
                <div class="col-sm-10">
                    <input type="text" name="username" class="form-control" id="username" placeholder="用户名">
                </div>
            </div>
            <div class="form-group">
                <label for="inputPassword3" class="col-sm-2 control-label">密码</label>
                <div class="col-sm-10">
                    <input type="password" name="password" class="form-control" id="inputPassword3" placeholder="密码">
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">登录</button>
                </div>
            </div>
        </form>


    </div>



{% endblock %}

axf/templates/market.html
{% extends 'base_main.html' %}
{% load static %}
{% block extCSS %}
{{ block.super }}
    <link rel="stylesheet" href="{% static 'app/market/market.css' %}">
{% endblock %}

{% block header %}
    <header><span> {{ title }} </span></header>

{% endblock %}
{% block content %}

    <div id="market">
        <aside>
            <ul>
                {% for foodtype in foodtypes %}
                    <li>
                        {% ifequal tid foodtype.typeid %}
                             <span class="yellowSlide"></span>
                        {% endifequal %}


                        <a href="{% url 'app:queryfood' foodtype.typeid '0' '0' %}">{{ foodtype.typename }}</a>
                    </li>
                {% endfor %}
                
            </ul>
        </aside>
        <section>
            <nav>
                <ul>
                    <li>
                        <span id="alltypebtn">全部类型
                            <span class="glyphicon glyphicon-chevron-down" id="type_down"></span>
                        </span>
                    </li>
                    <li>
                        <span id="showsortbtn">综合排序
                             <span class="glyphicon glyphicon-chevron-down" id="sort_down"></span>
                        </span>
                    </li>
                </ul>
            </nav>
            <menu>
                <ul>
                    {% for good in goods %}
                        <li>
                            <a href="">
                                <img src="{{ good.productimg }}" alt="{{ good.productname }}">
                                <article class="shoppingInfo">
                                    <h6>{{ good.productlongname }}</h6>
                                    <p class="detailTag"> <span>精选</span> <span></span> </p>
                                    <span  class="unit">{{ good.specifics }}</span>
                                    <p class="price"> <span>{{ good.price }}</span> <s> <span>{{ good.marketprice }}</span> </s></p>
                                </article>
                            </a>
                            <section>
                                <button  gid="{{ good.id }}" class="subShopping">-</button>
                                <span>0</span>
                                <button gid="{{ good.id }}" class="addShopping">+</button>
                            </section>
                        </li>
                    {% endfor %}

                </ul>
                <div id="typediv">
                    <div>
                        {% for ctype in ctypes %}
                            <a href="{% url 'app:queryfood' tid ctype.1 '0' %}"><span>{{ ctype.0 }}</span> </a>
                        {% endfor %}

                    </div>
                </div>
                <div id="sortdiv">
                    <div>
                        <a href="{% url 'app:queryfood' tid cid '0' %}"> <span>综合排序</span> </a>
                        <a href="{% url 'app:queryfood' tid cid '1' %}"> <span>销量排序</span> </a>
                        <a href="{% url 'app:queryfood' tid cid '2' %}"> <span>价格最低</span> </a>
                        <a href="{% url 'app:queryfood' tid cid '3' %}"> <span>价格最高</span> </a>

                    </div>
                </div>
            </menu>

        </section>
    </div>


{% endblock %}
{% block EXTJS %}
    <script src="{% static 'app/market/js/market.js' %}"></script>
{#    <link rel="stylesheet" href="{% static 'app/market/js/market.js' %}">#}
{% endblock %}

axf/templates/mine.html
{% extends 'base_main.html' %}
{% load static %}
{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'app/mine/mine.css' %}">
{% endblock %}

{% block content %}

    <div id="mine">
        <div class="fixed">
            <span class="glyphicon glyphicon-user"></span>
            {% if is_login %}
                 <p>{{ username }}</p>
            {% else %}
                <p><a href="{% url 'app:login' %}">未登录</a> </p>
            {% endif %}

            <p> <span class="glyphicon glyphicon-fire"></span> <span>等级</span> </p>
           {% if not is_login %}
                 <a id="regis" href=""> 注册</a>
           {% endif %}

            <p> <span class="glyphicon glyphicon-heart"></span>商品收藏</p>
        </div>
        <div class="mine">
            <p>
                <span>我的订单</span> <a>查看全部订单&gt;</a>
            </p>
            <nav id="nav">
                <ul>
                    <li>
                        <a href="">
                            <dl>
                                <dt>
                                    <span class="glyphicon glyphicon-usd"></span>
                                </dt>
                                <dd>待付款</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <dl>
                                <dt>
                                    <span class="glyphicon glyphicon-envelope"></span>
                                </dt>
                                <dd>待收货</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <dl>
                                <dt>
                                    <span class="glyphicon glyphicon-pencil"></span>
                                </dt>
                                <dd>待评价</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <dl>
                                <dt>
                                    <span class="glyphicon glyphicon-retweet"></span>
                                </dt>
                                <dd>收货/售后</dd>
                            </dl>
                        </a>
                    </li>

                </ul>
            </nav>
            <menu>
                <ul>
                    <li>
                        <a href="">
                            <dl>
                                <dt><span class="glyphicon glyphicon-bullhorn"></span></dt>
                                <dd>积分商城</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-credit-card"></span></dt>
							<dd>优惠券</dd>
						</dl>
					</a>
				</li>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-import"></span></dt>
							<dd>收货地址</dd>
						</dl>
					</a>
				</li>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-phone-alt"></span></dt>
							<dd>客服/反馈</dd>
						</dl>
					</a>
				</li>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-asterisk"></span></dt>
							<dd>关于我们</dd>
						</dl>
					</a>
				</li>
                </ul>
            </menu>
            {% if is_login %}
                <p><a href="{% url 'app:logout' %}">退出</a></p>
            {% endif %}

        </div>

    </div>


{% endblock %}